services:
  content_mirror:
    image: contentmirror
    build:
      context: .
      dockerfile: ContentMirror.Application/Dockerfile
    environment:
      - SiteConfig__ConnectionString=${DB_CONNECTION_STRING}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://seq:5341
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    volumes:
      - ./logs:/app/logs
    networks:
      - newstravel_app_network
  
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    volumes:
      - ./seq_data:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=Qwerty123_
    ports:
      - "5341:5341"
      - "8082:80"
    networks:
      - newstravel_app_network

networks:
  newstravel_app_network:
    external: true